In [30]:
import gensim
import tensorflow as tf
import numpy as np

In [19]:
from gensim.models import KeyedVectors
filename = 'GoogleNews-vectors-negative300.bin'
word_vector = KeyedVectors.load_word2vec_format(filename, binary=True, limit=500000)


In [6]:
tokenized_text = [['this', 'is', 'the', 'first', 'sentence', 'for', 'word2vec'],
                 ['this', 'is', 'the', 'second', 'sentence'],
                 ['yet', 'another', 'sentence'],
                 ['one', 'more', 'sentence'],
                 ['and', 'the', 'final', 'sentence']]

In [21]:
#Word to index in w2v
encoded_docs = []
for tokenized_sent in tokenized_text:
    encoded_sent = []
    for term in tokenized_sent:
        try:
            encoded_sent.append(word_vector[term].index)
        except:
            pass
    encoded_docs.append(encoded_sent)
encoded_docs

[[28, 4, 11, 56, 2303, 2],
 [28, 4, 11, 110, 2303],
 [506, 197, 2303],
 [45, 39, 2303],
 [11, 323, 2303]]

In [26]:
#Sentence Padding
mx = max([len(encoded_sent) for encoded_sent in encoded_docs])
print(mx)
X_w2v = tf.keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=mx, padding='post')
print(X_w2v)
print(X_w2v.shape)

6
[[  28    4   11   56 2303    2]
 [  28    4   11  110 2303    0]
 [ 506  197 2303    0    0    0]
 [  45   39 2303    0    0    0]
 [  11  323 2303    0    0    0]]
(5, 6)


In [37]:
#doc padding
dim = 2
X_w2v_post = []
for X_sent in X_w2v:
    tmp = []
    for i in X_sent:
        print(i)
        tmp.append(
            np.zeros((2,)) if i==0 else
            word_vector.get_vector(word_vector.index2word[i])
        )
    X_w2v_post.append(tmp)
X_w2v_post = np.array(X_w2v_post)
print(X_w2v_post.shape)
#X_w2v_post = X_w2v_post.reshape(X_w2v_post.shape[0], X_w2v_post.shape[1] * X_w2v_post.shape[2])
#print(X_w2v_post.shape)

28
4
11
56
2303
2
28
4
11
110
2303
0
506
197
2303
0
0
0
45
39
2303
0
0
0
11
323
2303
0
0
0
(5, 6)
